// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monospace2 {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("SessionCellController")]
	public partial class SessionCellController {
		
		[MonoTouch.Foundation.Connect("labelTime")]
		private MonoTouch.UIKit.UILabel labelTime {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelTime")));
			}
			set {
				this.SetNativeField("labelTime", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelTitle")]
		private MonoTouch.UIKit.UILabel labelTitle {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelTitle")));
			}
			set {
				this.SetNativeField("labelTitle", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelSubtitle")]
		private MonoTouch.UIKit.UILabel labelSubtitle {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelSubtitle")));
			}
			set {
				this.SetNativeField("labelSubtitle", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("cell")]
		private MonoTouch.UIKit.UITableViewCell cell {
			get {
				return ((MonoTouch.UIKit.UITableViewCell)(this.GetNativeField("cell")));
			}
			set {
				this.SetNativeField("cell", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("labelTimeEnd")]
		private MonoTouch.UIKit.UILabel labelTimeEnd {
			get {
				return ((MonoTouch.UIKit.UILabel)(this.GetNativeField("labelTimeEnd")));
			}
			set {
				this.SetNativeField("labelTimeEnd", value);
			}
		}
	}
}
